# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
group :development do
  gem "capistrano", "~> 3.19"
  gem "capistrano-rails", "~> 1.6"
  gem "capistrano-passenger", "~> 0.2.0"
  gem "capistrano-rvm"
  
  # Hỗ trợ Cronjob (Cần có ở đây để nạp task deploy)
  gem 'whenever', require: false

  # Gem hỗ trợ SSH Key hiện đại
  gem "ed25519", ">= 1.2", "< 2.0"
  gem "bcrypt_pbkdf", ">= 1.0", "< 2.0"
end
