# solr_contract Dockerfile
FROM solr:7.5.0
MAINTAINER An Tran "antm@meperia.com"
# There is no need to edit any configuration files at this time.
# Add any additional setup if necessary, such as copying configuration files.


